/**:
  delta_teleop_node:
    ros__parameters:
      left_stick_x_axis: 0
      left_stick_x_axis_type: "axis"
      left_stick_y_axis: 1
      left_stick_y_axis_type: "axis"
      right_stick_x_axis: 3
      right_stick_x_axis_type: "axis"
      right_stick_y_axis: 4
      right_stick_y_axis_type: "axis"

      directional_buttons_x_axis: 6
      directional_buttons_x_axis_type: "axis"
      directional_buttons_y_axis: 7
      directional_buttons_y_axis_type: "axis"

      l2_trigger: 2
      l2_trigger_type: "trigger"
      r2_trigger: 5
      r2_trigger_type: "trigger"

      cross_button: 0
      cross_button_type: "button"
      circle_button: 1
      circle_button_type: "button"
      triangle_button: 2
      triangle_button_type: "button"
      square_button: 3
      square_button_type: "button"

      l1_button: 4
      l1_button_type: "button"
      r1_button: 5
      r1_button_type: "button"
      l2_button: 6
      l2_button_type: "button"
      r2_button: 7
      r2_button_type: "button"

      share_button: 8
      share_button_type: "button"
      options_button: 9
      options_button_type: "button"
      ps_button: 10
      ps_button_type: "button"

      l3_stick_button: 11
      l3_stick_button_type: "button"
      r3_stick_button: 12
      r3_stick_button_type: "button"

      directional_buttons_up: 13
      directional_buttons_up_type: "button"
      directional_buttons_down: 14
      directional_buttons_down_type: "button"
      directional_buttons_left: 15
      directional_buttons_left_type: "button"
      directional_buttons_right: 16
      directional_buttons_right_type: "button"