/**:
  delta_teleop_node:
    ros__parameters:
      axis_left_stick_x: 0
      axis_left_stick_y: 1
      axis_right_stick_x: 3
      axis_right_stick_y: 4

      trigger_l2: 2
      trigger_r2: 5

      button_cross: 0
      button_circle: 1
      button_triangle: 2
      button_square: 3

      button_l1: 4
      button_r1: 5
      button_l2: 6
      button_r2: 7

      button_select: 8
      button_start: 9
      button_ps: 10

      button_l3_stick: 11
      button_r3_stick: 12

      button_directional_up: 13
      button_directional_down: 14
      button_directional_left: 15
      button_directional_right: 16