# An annotated version of dualshock4_mapping.yaml

# Name of the control device, used for logging in nodes
name: "test controller"

# A dictionary where the mapping is: input_name -> joy_index_number
# Make sure to take note of the input_name(s), you will use them for creating your control scheme
mapping:

  # For any inputs placed in the axes nested-list, make sure to label those inputs
  # starting with the letter 'a', preferably with "axis_..."
  axis_left_stick_x: 0
  axis_left_stick_y: 1
  axis_right_stick_x: 3
  axis_right_stick_y: 4

  axis_directional_buttons_x: 6
  axis_directional_buttons_y: 7

  # For any inputs placed in the axes nested-list but are actually triggers 
  # (when released have an output of 1, and when squeezed have an ouput of -1),
  # make sure to label those inputs starting with the letter 't', preferably with "trigger_..."
  trigger_l2: 2
  trigger_r2: 5

  # For any inputs placed in the buttons nested-list, make sure to label those inputs
  # starting with the letter 'b', preferably with "button_..."
  button_cross: 0
  button_circle: 1
  button_triangle: 2
  button_square: 3

  button_l1: 4
  button_r1: 5
  button_l2: 6
  button_r2: 7

  button_share: 8
  button_options: 9
  button_ps: 10

  button_l3_stick: 11
  button_r3_stick: 12